# Generated by Django 2.0.6 on 2018-07-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('nds_18', models.IntegerField(blank=True, default=0)),
                ('nds_10', models.IntegerField(blank=True, default=0)),
                ('nds_0', models.IntegerField(blank=True, default=0)),
                ('nds_no', models.IntegerField(blank=True, default=0)),
                ('sum', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDiscountMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(blank=True, default='', max_length=128)),
                ('markup_name', models.CharField(blank=True, default='', max_length=128)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('markup', models.IntegerField(blank=True, default=0)),
                ('discount_sum', models.IntegerField(blank=True, default=0)),
                ('markup_sum', models.IntegerField(blank=True, default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=256)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('operation_type', models.IntegerField()),
                ('total_sum', models.IntegerField()),
                ('cash_total_sum', models.IntegerField()),
                ('e_cash_total_sum', models.IntegerField()),
                ('nds_18', models.IntegerField(blank=True, default=0)),
                ('nds_10', models.IntegerField(blank=True, default=0)),
                ('nds_0', models.IntegerField(blank=True, default=0)),
                ('nds_no', models.IntegerField(blank=True, default=0)),
                ('store', models.CharField(blank=True, default='', max_length=256)),
                ('retail_place_address', models.CharField(blank=True, default='', max_length=256)),
                ('store_inn', models.CharField(blank=True, default='', max_length=13)),
                ('taxation_type', models.IntegerField(blank=True, default=0)),
                ('kkt_reg_id', models.CharField(blank=True, default='', max_length=21)),
                ('shift_number', models.IntegerField(blank=True, default=0)),
                ('fiscal_document_number', models.IntegerField(blank=True, default=0)),
                ('fiscal_drive_number', models.CharField(blank=True, default='', max_length=17)),
                ('request_number', models.IntegerField(blank=True, default=0)),
                ('operator', models.CharField(blank=True, default='', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDiscountMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(blank=True, default='', max_length=128)),
                ('markup_name', models.CharField(blank=True, default='', max_length=128)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('markup', models.IntegerField(blank=True, default=0)),
                ('discount_sum', models.IntegerField(blank=True, default=0)),
                ('markup_sum', models.IntegerField(blank=True, default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='StornoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('nds_18', models.IntegerField(blank=True, default=0)),
                ('nds_10', models.IntegerField(blank=True, default=0)),
                ('nds_0', models.IntegerField(blank=True, default=0)),
                ('nds_no', models.IntegerField(blank=True, default=0)),
                ('sum', models.IntegerField(blank=True, default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='StornoItemDiscountMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(blank=True, default='', max_length=128)),
                ('markup_name', models.CharField(blank=True, default='', max_length=128)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('markup', models.IntegerField(blank=True, default=0)),
                ('discount_sum', models.IntegerField(blank=True, default=0)),
                ('markup_sum', models.IntegerField(blank=True, default=0)),
                ('storno_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.StornoItem')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.Receipt'),
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fni.Receipt'),
        ),
    ]
