# Generated by Django 2.0.6 on 2018-08-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordforemail',
            name='email',
        ),
        migrations.DeleteModel(
            name='PasswordForEmail',
        ),
    ]
